### ISSUE TITLE
Object editor component

### ISSUE THREAD

**Issue by CrackerakiUA** [windmichael/ngx-acuw#3]
Hey, your package looks perspective, do you have in plans to add more components? What about 3D components?

**Comment by windmichael** [comment]
Hi. Yes, I definitely want to add more components to the library. 
The next component I plan to add would be something like a carousel. I use this on my [homepage](https://michael-wind.firebaseapp.com/work)

Or do you have any other suggestion of a 3D component you would like to have?

**Comment by CrackerakiUA** [comment]
For start, looks amazing. On my case, I need simply to drop 3D objects into an room and update them live.

**Comment by windmichael** [comment]
I don't clearly understand what you want to have. 
Where do you get this 3D objects from? Do you create the objects by yourself and pass it to the component then?
What about the other scene properties like light, camera settings and so on? Do you expect them to be configurable via an API of the component? It would be quite a huge effort to make all those settings configurable and maintain it.

**Comment by CrackerakiUA** [comment]
More or less similar to this one: https://threejs.org/examples/#webgl_interactive_voxelpainter
Objects will be prepared, already made. Light just at one place, camera like in view mode.
I am open to contribute and I believe that this can be useful on many business areas.

**Comment by windmichael** [comment]
I created a new feature branch for this request. Let's see when I have time working on that. I will keep you informed, as soon I have something to show. At this stage I would be glad then, if you could support and contribute.

**Comment by windmichael** [comment]
I just created a some basic functions for adding objects into a scene. But I feel the whole thing ends up like the threejs editor. What do you think? This is the feature branch [issue3 branch](https://github.com/windmichael/ngx-acuw/tree/windmichael/issue3).
