### ISSUE TITLE
Responsive lightbox for devices

### ISSUE THREAD

**Issue by pasblin** [windmichael/ngx-acuw#6]

**Comment by windmichael** [comment]
Please describe this issue in detail. The lightbox switches to full-screen for devices, which have a width lower than 600px. In addition, you can force the lightbox going into full-screen mode by setting the 'forceFullscreen' property. If you can describe your request, I could change the current behavior.

**Comment by pasblin** [comment]
Hello, I have tested the library wrong, when doing it from [here](https://windmichael.github.io/ngx-acuw/lightbox)  the images were not complete but when doing it from [here](https://stackblitz.com/edit/angular-ngx-acuw-lightbox) everything works ok, I close the issue.

Fantastic library :)
